services:
  - type: web
    name: incident-alerts
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn incident_alerts.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
